version: "3.7"

networks:
  evaluation:


services:
  core:
    build:
      context: .
      args:
        user: laravel
        uid: 1000
    ports:
      - "9000:9000"
    restart: unless-stopped
    working_dir: /var/www/evaluation
    volumes:
      - ./:/var/www/evaluation
    networks:
      - evaluation

  nginx:
    image: nginx:stable-alpine
    container_name: evaluation-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/evaluation
      - ./dockerconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - core
      - mysql
    networks:
      - evaluation
  mysql:
    image: mysql:8.0
    container_name: evaluation-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
      - ./dockerconfig/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: evaluation
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - evaluation
